version: "3.4"

services:

  api:
    build:
      context: .
      network: host
    image: example-moleculer
    container_name: example-moleculer-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats

  greeter:
    build:
      context: .
      network: host
    image: example-moleculer
    container_name: example-moleculer-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    links:
      - nats
    depends_on:
      - nats

  nats:
    image: nats
    ports:
      - "4222:4222"
